name = "inspilot"
compatibility_date = "2024-11-28"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "MY_DB"
database_name = "inspilot"
database_id = "15f5707c-277c-4a8d-ab44-601d35c22b93"
migrations_dir = "./app/db/migrations"

# 添加本地开发配置
[env.preview.d1_databases]
binding = "MY_DB"
database_name = "inspilot"
database_id = "15f5707c-277c-4a8d-ab44-601d35c22b93"
migrations_dir = "./app/db/migrations"
# 指定本地数据库文件路径
database_filename = ".dev.db"