name = "inspilot"
compatibility_date = "2024-04-05"
compatibility_flags = [
  "nodejs_compat",
  "nodejs_als",
  "experimental"
]

pages_build_output_dir = "./build/client"

[[d1_databases]]
binding = "MY_DB"
database_name = "inspilot"
database_id = "15f5707c-277c-4a8d-ab44-601d35c22b93"
migrations_dir = "app/db/migrations"

[build]
command = "npm run build"

[env.dev]
[[env.dev.d1_databases]]
binding = "MY_DB"
database_name = "inspilot"
database_id = "15f5707c-277c-4a8d-ab44-601d35c22b93"